---
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - VALIDATION=duckdns
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
      - URL=magnumlab.duckdns.org
      - SUBDOMAINS=wildcard,dash,www
      #- DNSPLUGIN=cloudflare
      #- REAL_IP_FROM=cloudflare
      - EMAIL=${EMAIL}
      - SWAG_AUTORELOAD=true          # Highly recommended!
    volumes:
      - ./swag-config:/config
      - ./duckdns.ini:/config/dns-conf/duckdns.ini:ro
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"   # QUIC
    networks:
      - proxy_net
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    command:
      - "--trusted-origins=dash.magnumlab.duckdns.org"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy_net
    restart: unless-stopped

networks:
  proxy_net:
    external: true

volumes:
  portainer_data:
  wp_data:
    external: true